name: Build and Deploy Jupyter Book

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install jupyter-book
    - name: Build Jupyter Book HTML
      run: |
        jupyter-book build .

    - name: Deploy to GitHub Pages using Jupyter Book Action
      uses: executablebooks/github-action-jupyter-book-deploy@v1
      with:
        path-to-book: ./_build/html
        branch: gh-pages  # assuming you want to deploy to the gh-pages branch
        github_token: ${{ secrets.GITHUB_TOKEN }}
